server:
  port: 8082
spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5433/fraud
    username: frank
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
